// 8x8 monochrome glyphs. 'A' is the accent slot, recoloured per use.

const P = { A: '#a855f7' }
const g = (grid) => ({ w: 8, h: 8, palette: P, grid })

export const ICONS = {
  home: g([
    '...AA...',
    '..A..A..',
    '.A....A.',
    'AAAAAAAA',
    '.A....A.',
    '.A.AA.A.',
    '.A.AA.A.',
    '.AAAAAA.',
  ]),
  dumbbell: g([
    '........',
    'AA....AA',
    'AA....AA',
    'AAAAAAAA',
    'AAAAAAAA',
    'AA....AA',
    'AA....AA',
    '........',
  ]),
  trophy: g([
    'AAAAAAAA',
    'AAAAAAAA',
    'AAAAAAAA',
    '.AAAAAA.',
    '..AAAA..',
    '...AA...',
    '..AAAA..',
    '.AAAAAA.',
  ]),
  chat: g([
    'AAAAAAA.',
    'A.....A.',
    'A.AAA.A.',
    'A.....A.',
    'A.AAA.A.',
    'AAAAAAA.',
    '.AA.....',
    '.A......',
  ]),
  person: g([
    '..AAAA..',
    '..AAAA..',
    '..AAAA..',
    '........',
    '.AAAAAA.',
    'AAAAAAAA',
    'AAAAAAAA',
    '.AA..AA.',
  ]),
  flame: g([
    '...AA...',
    '..AAAA..',
    '..AAAA..',
    '.AAAAAA.',
    'AAAAAAAA',
    'AAAAAAAA',
    'AA.AA.AA',
    '.A.AA.A.',
  ]),
  core: g([
    '..AAAA..',
    '.AAAAAA.',
    'AAA..AAA',
    'AA....AA',
    'AA....AA',
    'AAA..AAA',
    '.AAAAAA.',
    '..AAAA..',
  ]),
  bolt: g([
    '....AA..',
    '...AA...',
    '..AAA...',
    '.AAAAA..',
    '...AA...',
    '..AA....',
    '.AA.....',
    '.A......',
  ]),
  chest: g([
    '..AAAA..',
    '.AAAAAA.',
    'AAAAAAAA',
    'AAAAAAAA',
    'AAA..AAA',
    'AAA..AAA',
    'AAAAAAAA',
    'AAAAAAAA',
  ]),
  skull: g([
    '.AAAAAA.',
    'AAAAAAAA',
    'AA.AA.AA',
    'AA.AA.AA',
    'AAAAAAAA',
    'AA.AA.AA',
    '.AAAAAA.',
    '..A..A..',
  ]),
  crosshair: g([
    '...AA...',
    '...AA...',
    '.AAAAAA.',
    'AA.AA.AA',
    'AA.AA.AA',
    '.AAAAAA.',
    '...AA...',
    '...AA...',
  ]),
  shield: g([
    'AAAAAAAA',
    'AAAAAAAA',
    'AAAAAAAA',
    '.AAAAAA.',
    '.AAAAAA.',
    '..AAAA..',
    '...AA...',
    '........',
  ]),
  check: g([
    '........',
    '......AA',
    '.....AA.',
    'A...AA..',
    'AA.AA...',
    '.AAA....',
    '..A.....',
    '........',
  ]),
  lock: g([
    '..AAAA..',
    '.AA..AA.',
    '.AA..AA.',
    'AAAAAAAA',
    'AAA..AAA',
    'AAA..AAA',
    'AAAAAAAA',
    '........',
  ]),
  plus: g([
    '........',
    '...AA...',
    '...AA...',
    '.AAAAAA.',
    '.AAAAAA.',
    '...AA...',
    '...AA...',
    '........',
  ]),
  spark: g([
    '...A....',
    '.A.A.A..',
    '..AAA...',
    'AAAAAAA.',
    '..AAA...',
    '.A.A.A..',
    '...A....',
    '........',
  ]),
  heart: g([
    '.AA..AA.',
    'AAAAAAAA',
    'AAAAAAAA',
    'AAAAAAAA',
    '.AAAAAA.',
    '..AAAA..',
    '...AA...',
    '........',
  ]),
  boot: g([
    '.AA.....',
    'AAAA....',
    'AAAA....',
    '.AA.....',
    '.....AA.',
    '....AAAA',
    '....AAAA',
    '.....AA.',
  ]),
  // Affordance marker for rows that open into something else.
  chevron: g([
    '..AA....',
    '...AA...',
    '....AA..',
    '.....AA.',
    '.....AA.',
    '....AA..',
    '...AA...',
    '..AA....',
  ]),
  play: g([
    'AAAAAAAA',
    'A......A',
    'A.AA...A',
    'A.AAAA.A',
    'A.AAAA.A',
    'A.AA...A',
    'A......A',
    'AAAAAAAA',
  ]),
  sun: g([
    '...AA...',
    'A.AAAA.A',
    '.AAAAAA.',
    'AAAAAAAA',
    'AAAAAAAA',
    '.AAAAAA.',
    'A.AAAA.A',
    '...AA...',
  ]),
  moon: g([
    '..AAAA..',
    '.AAAA...',
    'AAAA....',
    'AAA.....',
    'AAA.....',
    'AAAA....',
    '.AAAA...',
    '..AAAA..',
  ]),
  wheel: g([
    '..AAAA..',
    '.A.AA.A.',
    'A..AA..A',
    'AAAAAAAA',
    'AAAAAAAA',
    'A..AA..A',
    '.A.AA.A.',
    '..AAAA..',
  ]),
  lotus: g([
    '...AA...',
    '..AAAA..',
    '.A.AA.A.',
    'AA.AA.AA',
    'AAAAAAAA',
    '.AAAAAA.',
    '..AAAA..',
    '........',
  ]),
  hold: g([
    '.AA..AA.',
    '.AA..AA.',
    '.AAAAAA.',
    'AAAAAAAA',
    'AAAAAAAA',
    '.AAAAAA.',
    '..AAAA..',
    '...AA...',
  ]),
  wave: g([
    '........',
    '........',
    '.AA...A.',
    'A..A.A.A',
    '......A.',
    '.AA...A.',
    'A..A.A.A',
    '......A.',
  ]),
  stop: g([
    '........',
    '.AAAAAA.',
    '.AAAAAA.',
    '.AAAAAA.',
    '.AAAAAA.',
    '.AAAAAA.',
    '.AAAAAA.',
    '........',
  ]),
  pause: g([
    '........',
    '.AA..AA.',
    '.AA..AA.',
    '.AA..AA.',
    '.AA..AA.',
    '.AA..AA.',
    '.AA..AA.',
    '........',
  ]),
  pin: g([
    '..AAA...',
    '.A...A..',
    '.A.A.A..',
    '.A...A..',
    '..A.A...',
    '...A....',
    '...A....',
    '...A....',
  ]),
  swap: g([
    '..A.....',
    '.AA.....',
    'AAAAAAA.',
    '.AA.....',
    '.....AA.',
    '.AAAAAAA',
    '.....AA.',
    '......A.',
  ]),
  link: g([
    '..AAA...',
    '.A...A..',
    'A..AA.A.',
    'A.AAAA.A',
    'A.AAAA.A',
    '.A.AA.A.',
    '..A..A..',
    '...AAA..',
  ]),
}
