// Generated by tools/import_logos.py from art/logos/. Do not edit by hand —
// re-run the tool instead.
//
// Empty until the logo files are added. Every game then falls back, in order,
// to its Simple Icons mark and then to a monogram, so the profile is never
// broken while the set is incomplete.

/** Game id to base64 PNG, 96x96, background knocked out and centred. */
export const LOGO_ART = {}
