/**
 * Pine Script v6 generation.
 *
 * TradingView's supported path is a script you paste into the Pine editor, so
 * that is what this produces. It is also the honest one: the emitted strategy
 * uses the *same* rules and the same cost assumptions as `backtest.js`, so
 * TradingView's Strategy Tester becomes an independent check on our numbers
 * rather than a second, differently-wrong answer.
 *
 * If the two disagree, that is a finding worth chasing — usually fill timing or
 * fee handling.
 */

const HEADER = (title) => `// ${title}
// Generated by memebot. Paste into TradingView's Pine editor.
//
// The rules and costs here mirror bot/src/ta/backtest.js so the two can be
// compared. If TradingView's result differs materially, trust neither until
// you know why.`;

/**
 * Strategy script matching `rsiVolumeSignal` + the ATR exit model.
 *
 * `process_orders_on_close=false` is deliberate: it fills on the next bar's
 * open, which is what the local engine does. Setting it true would let the
 * strategy enter on the bar that produced the signal and inflate every result.
 */
export function strategyScript({
  rsiPeriod = 14,
  rsiBelow = 30,
  volumePeriod = 20,
  minVolumeRatio = 3,
  atrPeriod = 14,
  stopAtrMult = 2,
  targetAtrMult = 3,
  maxBars = 24,
  feePct = 0.04,
  slippageTicks = 2,
  riskPerTradePct = 2,
} = {}) {
  return `${HEADER('RSI + Volume Surge — long only')}
//@version=6
strategy("RSI + Volume Surge (memebot)",
     overlay              = true,
     initial_capital      = 10000,
     default_qty_type     = strategy.percent_of_equity,
     default_qty_value    = 100,
     commission_type      = strategy.commission.percent,
     commission_value     = ${feePct},
     slippage             = ${slippageTicks},
     process_orders_on_close = false,
     calc_on_every_tick   = false)

// ── Inputs ───────────────────────────────────────────────────────────────────
rsiLen      = input.int(${rsiPeriod},  "RSI length",            minval = 2,   group = "Entry")
rsiTrigger  = input.float(${rsiBelow}, "RSI below",             minval = 1,   group = "Entry")
volLen      = input.int(${volumePeriod}, "Volume baseline",     minval = 2,   group = "Entry")
volMult     = input.float(${minVolumeRatio}, "Volume ≥ x average", minval = 1, step = 0.1, group = "Entry")

atrLen      = input.int(${atrPeriod},  "ATR length",            minval = 2,   group = "Exit")
stopMult    = input.float(${stopAtrMult},   "Stop (ATR)",       minval = 0.1, step = 0.1, group = "Exit")
targetMult  = input.float(${targetAtrMult}, "Target (ATR)",     minval = 0.1, step = 0.1, group = "Exit")
maxBarsHeld = input.int(${maxBars},    "Time stop (bars)",      minval = 1,   group = "Exit")
riskPct     = input.float(${riskPerTradePct}, "Risk per trade %", minval = 0.1, step = 0.1, group = "Risk")

// ── Conditions ───────────────────────────────────────────────────────────────
rsiValue  = ta.rsi(close, rsiLen)
volAvg    = ta.sma(volume, volLen)
volRatio  = volAvg > 0 ? volume / volAvg : 0.0
atrValue  = ta.atr(atrLen)

// bar_index guard keeps the warm-up bars out: an indicator that is not yet
// defined must not produce a signal.
warmedUp  = bar_index > math.max(rsiLen, volLen, atrLen)
entryCond = warmedUp and rsiValue < rsiTrigger and volRatio >= volMult

// ── Sizing ───────────────────────────────────────────────────────────────────
// Position size so that a stop-out costs riskPct of equity, not a fixed notional.
stopDist  = atrValue * stopMult
qty       = stopDist > 0 ? (strategy.equity * riskPct / 100) / stopDist : 0.0

if entryCond and strategy.position_size == 0 and qty > 0
    strategy.entry("long", strategy.long, qty = qty)

if strategy.position_size > 0
    entryPrice = strategy.position_avg_price
    strategy.exit("exit", from_entry = "long",
         stop  = entryPrice - stopDist,
         limit = entryPrice + atrValue * targetMult)

    if bar_index - strategy.opentrades.entry_bar_index(0) >= maxBarsHeld
        strategy.close("long", comment = "time stop")

// ── Plots ────────────────────────────────────────────────────────────────────
plotshape(entryCond, title = "Signal", style = shape.triangleup,
     location = location.belowbar, color = color.new(color.teal, 0), size = size.tiny)

bgcolor(entryCond ? color.new(color.teal, 88) : na, title = "Signal bar")
`;
}

/**
 * The requested oscillator: momentum weighted by the conviction behind it.
 *
 * **What "whale activity" means here.** Pine cannot see wallets, order books or
 * individual fills — on a chart, the only footprint a large participant leaves
 * is unusually heavy volume relative to that symbol's own norm. So this uses a
 * volume z-score signed by bar direction as a *proxy*. It is a real signal, but
 * it is not wallet tracking: a burst of retail activity looks identical. Actual
 * whale tracking needs on-chain data or exchange trade-level feeds, neither of
 * which is available inside Pine.
 */
export function whaleMomentumScript({
  momentumPeriod = 14,
  volumePeriod = 20,
  whaleSigma = 2,
  smoothing = 9,
} = {}) {
  return `${HEADER('Whale-Weighted Momentum (WWM)')}
//
// IMPORTANT — what "whale activity" is in this script:
// Pine cannot see wallets, order books, or individual fills. The only footprint
// a large participant leaves on a chart is volume that is unusual FOR THIS
// SYMBOL. This script therefore uses a volume z-score signed by bar direction
// as a proxy for large directional flow. A burst of retail activity looks the
// same. Real whale tracking needs on-chain or trade-level data, which is not
// available here — treat this as "conviction behind the move", not "a whale".
//@version=6
indicator("Whale-Weighted Momentum", shorttitle = "WWM", overlay = false)

momLen    = input.int(${momentumPeriod}, "Momentum length",  minval = 2, group = "Momentum")
volLen    = input.int(${volumePeriod},   "Volume baseline",  minval = 2, group = "Flow")
sigma     = input.float(${whaleSigma},   "Large-flow threshold (σ)", minval = 0.5, step = 0.1, group = "Flow")
smoothLen = input.int(${smoothing},      "Smoothing",        minval = 1, group = "Momentum")

// ── Momentum: RSI recentred so that zero means "no trend" ────────────────────
mom = (ta.rsi(close, momLen) - 50) * 2

// ── Flow: how unusual is this bar's volume, and which way did it push? ───────
volMean = ta.sma(volume, volLen)
volSd   = ta.stdev(volume, volLen)
volZ    = volSd > 0 ? (volume - volMean) / volSd : 0.0
dir     = close > open ? 1 : close < open ? -1 : 0
flow    = volZ * dir

// ── Cross the two ────────────────────────────────────────────────────────────
// A big move on ordinary volume is discounted; an ordinary move on heavy
// volume is amplified. The clamp keeps the multiplier positive so the
// oscillator never flips sign purely because volume was light.
raw    = mom * (1 + math.max(flow, -0.9))
wwm    = ta.ema(raw, smoothLen)
signal = ta.ema(wwm, smoothLen * 2)

// ── Divergence: price and flow disagreeing is the interesting state ──────────
// Momentum up while large flow is selling (or the reverse) tends to precede a
// reversal more often than either reading does alone.
bearishDiv = mom > 0 and flow < -sigma
bullishDiv = mom < 0 and flow >  sigma
whaleBar   = math.abs(volZ) >= sigma

// ── Plots ────────────────────────────────────────────────────────────────────
plot(wwm,    title = "WWM",    color = wwm >= 0 ? color.new(color.teal, 0) : color.new(color.red, 0), linewidth = 2)
plot(signal, title = "Signal", color = color.new(color.orange, 30), linewidth = 1)
hline(0, "Zero", color = color.new(color.gray, 50), linestyle = hline.style_dashed)

plotshape(bullishDiv, title = "Bullish divergence", style = shape.triangleup,
     location = location.bottom, color = color.new(color.teal, 0), size = size.tiny)
plotshape(bearishDiv, title = "Bearish divergence", style = shape.triangledown,
     location = location.top,    color = color.new(color.red, 0),  size = size.tiny)

bgcolor(whaleBar ? color.new(dir > 0 ? color.teal : color.red, 90) : na, title = "Large-flow bar")

alertcondition(ta.crossover(wwm, signal),  title = "WWM crosses up",   message = "WWM crossed above its signal line")
alertcondition(ta.crossunder(wwm, signal), title = "WWM crosses down", message = "WWM crossed below its signal line")
alertcondition(bearishDiv, title = "Bearish divergence", message = "Momentum up, large flow selling")
`;
}

/** A screener alert to attach to a watchlist, matching the CLI's conditions. */
export function screenerAlertScript({ rsiPeriod = 14, rsiBelow = 30, volumePeriod = 20, minVolumeRatio = 3 } = {}) {
  return `${HEADER('Screener alert — RSI + volume surge')}
//@version=6
indicator("RSI + Volume Screener (memebot)", overlay = true)

rsiLen     = input.int(${rsiPeriod}, "RSI length",   minval = 2)
rsiTrigger = input.float(${rsiBelow}, "RSI below",   minval = 1)
volLen     = input.int(${volumePeriod}, "Volume baseline", minval = 2)
volMult    = input.float(${minVolumeRatio}, "Volume ≥ x average", minval = 1, step = 0.1)

rsiValue = ta.rsi(close, rsiLen)
volAvg   = ta.sma(volume, volLen)
volRatio = volAvg > 0 ? volume / volAvg : 0.0
hit      = bar_index > math.max(rsiLen, volLen) and rsiValue < rsiTrigger and volRatio >= volMult

plotshape(hit, title = "Hit", style = shape.labeldown, location = location.abovebar,
     color = color.new(color.teal, 0), textcolor = color.white, text = "RSI+VOL", size = size.tiny)

// Attach on any chart, then "Add alert" with "Any alert() function call" so one
// alert covers a whole watchlist.
if hit
    alert(str.format("{0}: RSI {1,number,#.#} · volume {2,number,#.##}x average",
         syminfo.ticker, rsiValue, volRatio), alert.freq_once_per_bar_close)
`;
}

/**
 * Draw one specific idea's levels on a TradingView chart.
 *
 * This is the bridge. I cannot draw on your chart for you — but the levels,
 * entry, stop and targets are all just numbers, and a Pine overlay renders them
 * exactly where the analysis put them. Paste it, and the chart shows the same
 * picture the dashboard does.
 *
 * The values are baked in as inputs rather than recomputed, so what you see is
 * the idea as it was generated, not a moving recalculation that quietly drifts
 * away from the write-up.
 */
export function ideaScript(idea) {
  const { symbol, interval, setup, structure } = idea;
  const long = setup.side === 'long';
  const price = (value) => Number(value).toPrecision(8);

  const levelLines = structure.levels
    .map((level, index) => {
      const kind = level.price < structure.price ? 'support' : 'resistance';
      return `lvl${index} = input.float(${price(level.price)}, "${kind} · ${level.touches} touches", group = "Structure")`;
    })
    .join('\n');

  const levelPlots = structure.levels
    .map((level, index) => {
      const kind = level.price < structure.price ? 'support' : 'resistance';
      const colour = kind === 'support' ? 'color.new(color.teal, 40)' : 'color.new(color.maroon, 40)';
      return `plot(lvl${index}, title = "Level ${index + 1}", color = ${colour}, style = plot.style_linebr, linewidth = 1)`;
    })
    .join('\n');

  return `${HEADER(`${symbol} ${interval} — ${setup.side.toUpperCase()} setup`)}
//
// Generated for ${symbol} on ${interval} at ${price(structure.price)}.
// Levels are fixed values, not recalculated — this is the idea as written up.
//@version=6
indicator("${symbol} ${setup.side} setup (memebot)", overlay = true)

entryPrice = input.float(${price(setup.entry)},     "Entry",    group = "Trade")
stopPrice  = input.float(${price(setup.stop)},      "Stop",     group = "Trade")
target1    = input.float(${price(setup.targets[0])}, "Target 1", group = "Trade")
${setup.targets[1] ? `target2    = input.float(${price(setup.targets[1])}, "Target 2", group = "Trade")` : 'target2    = float(na)'}

${levelLines}

// ── Trade levels ─────────────────────────────────────────────────────────────
entryLine  = plot(entryPrice, title = "Entry",    color = color.new(color.orange, 0), linewidth = 2)
stopLine   = plot(stopPrice,  title = "Stop",     color = color.new(color.red, 0),    linewidth = 2)
target1Ln  = plot(target1,    title = "Target 1", color = color.new(color.green, 0),  linewidth = 2)
plot(target2, title = "Target 2", color = color.new(color.green, 45), linewidth = 1)

// Risk shaded against reward, so the ratio is visible rather than asserted.
fill(entryLine, stopLine,  color = color.new(color.red, 88),   title = "Risk")
fill(entryLine, target1Ln, color = color.new(color.green, 88), title = "Reward")

// ── Structure ────────────────────────────────────────────────────────────────
${levelPlots}

// ── Label ────────────────────────────────────────────────────────────────────
if barstate.islast
    label.new(bar_index + 3, entryPrice,
         text  = "${setup.side.toUpperCase()} · ${setup.riskReward.toFixed(2)}R\\nneeds ${(setup.breakEvenWinRate * 100).toFixed(0)}% win rate",
         style = label.style_label_left,
         color = color.new(${long ? 'color.teal' : 'color.maroon'}, 15),
         textcolor = color.white,
         size  = size.small)

alertcondition(ta.crossunder(close, stopPrice), title = "Stop breached",
     message = "${symbol}: price closed through the stop — idea invalidated")
alertcondition(ta.crossover(close, target1),    title = "Target 1 reached",
     message = "${symbol}: first target reached")
`;
}
